client/client/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

clients/urls.py
from django.contrib import admin
from django.urls import path, include
from clients import views

app_name = "clients"
urlpatterns = [
    path(r"dashboard",views.display_menu,name= 'dashboard'),
    path(r"get_function_choosen", views.get_function_choosen,name='Function'),
    path(r"deposit",views.deposit,name="Deposit"),
    path(r"withdraw",views.withdraw,name="Withdraw"),
    path(r"transfer",views.transfer,name="transfer"),
    path(r"modification",views.modification,name="modification"),
    path(r"recharge",views.recharge,name="recharge")
    
    
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
app_name = "home"
urlpatterns = [
    path("",views.home,name= 'home'),
    path("about",views.about, name="about"),
    path("services", views.services, name="views"),
    path("contact",views.contact, name="contact"),
    path("faqs", views.faqs, name="faqs"),
    path("signup",views.signup, name="signup"),
    path("signin", views.signin, name="signin"),    
    path('signout',views.signout, name='signout'),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from home import urls
from clients import urls

admin.site.site_header = "Bank Database Management System"
admin.site.site_title = "Bank Database Management System"
admin.site.index_title = "Welcome to My BDMS"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('',include('home.urls')),
    path('clients/',include("clients.urls"))
]

templates/Transfer.html
{% extends 'user_account.html' %}
{% block title %} Transfer {% endblock title %}
{% block body %}
<table width=70% height=60%>
<div id="edit_details" style="float:right;">
    <button type="button" id="edit_button"><a href="{% url 'clients:dashboard' %}">Home</a></button>
</div>
<tr>
    <td></td>

    <td>

        <div id="details_box">
            <form name="transfer_details" action="transfer" method="POST">
                <table id="details_table" cellpadding=5px;>
                    {% if accounts %}
                    {% csrf_token %}
                    <tr>
                        <td>Amount to Transfer :</td>
                        <td><input type="text" name="amount" placeholder="Amount"></td>
                    </tr>
                    <tr>
                        <td> Transfer to account Number :</td>
                        <td><input type="text" name="acc_no" placeholder="Account number"></td>
                    </tr>

                    <tr>
                        <td></td>
                        <!--<td><input type="button" value="Withdraw"></td>-->
                        <td><button>Transfer</button></td>
                    </tr>
                    {% else %}
                        <tr> <td> New Customer. No accounts yet. </td></tr>
                    {% endif %}
                    <tr>
                        <td><span>{{msg|safe}}</span></td>
                    </tr>
                    <tr>
                        <td> <small>By Withdrawing money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br></td>
                    </tr>
                </table>
            </form>
            
           
            
        </div>
    </td>
</tr>
</table>
{% endblock body%}

templates/about.html
{% extends 'base.html' %}
{% block title %} About {% endblock title %}
{% block body %}
This is my About body
{% endblock body%}

templates/balance_enquiry.html
{% extends 'user_account.html' %}
{% block title %} Balance Enquiry {% endblock title %}
{% block body %}
<div id="edit_details" style="float:right;">
                        <button type="button" id="edit_button"><a href="{% url 'clients:dashboard' %}">Home</a></button>
                    </div>
   
<h1 style="font-size:46px;text-align:center;"> Balance Enquiry </h1>
<table id="details_table" cellpadding=5px;>
<tr>
    <td>Account No : {{ accounts.Accno }}</td>
</tr>
<tr>
    <td>Amount in Your Account  : PKR. {{ accounts.Balance }}</td>
</tr>
</table>
{% endblock body%}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %} | Bank Database Management System</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Bank Database Management System</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About us</a>
              <li class="nav-item">
                <a class="nav-link" href="/faqs">FAQs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contact">Contact us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signin">Sign Up/ Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin Log In</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- Optional JavaScript; choose one of the two! -->
{% if messages%}
{%for message in messages%}
<div class="alert alert-{{message.tags}}" role="alert">
  {{message}}
</div>
  {% endfor %}
  {% endif %}
    {% block body %} {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %} Contact {% endblock title %}
{% block body %}


<div class="container-fluid px-0 center">
    <form method="POST" action="/contact">
        {% csrf_token %}
        <div class="mb-3">
          <label for="name" class="form-label">Full Name</label>
          <input type="name" class="form-control" id="name" name="name">
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" name="email" >
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>
        <div class="mb-3">
          <label for="message" class="form-label">Your Message</label>
          <input type="message" class="form-control" id="message" name="message">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
<!--Section: Contact v.2-->
{% endblock body%}

templates/deposit.html
{% extends 'user_account.html' %}
{% block title %} Deposit {% endblock title %}
{% block body %}
<table width=70% height=60%>
    
<div id="edit_details" style="float:right;">
    <button type="button" id="edit_button"><a href="{% url 'clients:dashboard' %}">Home</a></button>
</div>
    <tr>
        <td></td>

        <td>

            <div id="details_box">
                <form name="deposit_details" action="deposit" method="POST">
                    <table id="details_table" cellpadding=5px;>
                        {% if accounts %}
                       {% csrf_token %}
                        <tr>
                            <td>Amount to be deposited :</td>
                            <td><input type="text" name="amount" placeholder="Amount"></td>
                        </tr>
                        <tr>
                            <td> Deposit into account : {{ accounts.Accno }}</td>
                        </tr>

                        <tr>
                            <td></td>
                            <!--<td><input type="button" value="Withdraw"></td>-->
                            <td><button>Deposit</button></td>
                        </tr>
                        {% else %}
                            <tr> <td> New Customer. No accounts yet. </td></tr>
                        {% endif %}
                        <tr>
                            <td><span>{{msg|safe}}</span></td>
                        </tr>
                        <tr>
                            <td> <small>By transferring money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br></td>
                        </tr>
                    </table>
                </form>
            </div>
        </td>
    </tr>
</table>
{% endblock body%}

templates/details.html
{% extends 'user_account.html' %}
{% block title %} Details {% endblock title %}
{% block body %}
<div id="edit_details" style="float:right;">
                        <button type="button" id="edit_button"><a href="{% url 'clients:dashboard' %}">Home</a></button>
                    </div>
   
<h1 style="font-size:46px;text-align:center;" > Personal Details </h1>

<h2 style="font-size:28px;">User Name : {{ customer.name }} </h2>
<h2 style="font-size:28px;">Phone Number : {{ customer.phone }} </h2>
<h2 style="font-size:28px;">Email : {{ customer.email }} </h2>
<h2 style="font-size:28px;">Cnic : {{ customer.cnic }} </h2>
{% endblock body%}

templates/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}
{% block body %}
<div class="container-fluid">

      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://media.istockphoto.com/photos/trading-charts-on-a-display-picture-id1317587887" class="d-block w-100" alt="BankImage1" width="300" height="700" style="padding:20px">
            <div class="carousel-caption d-none d-md-block bg-black">
              <h5>First Bank Database Management System</h5>
            <p>It is one the First Online Bank Database Management System Started in town.</p>
          </div>
          </div>
          <div class="carousel-item">
            <img src="https://media.istockphoto.com/photos/bank-employee-explains-bank-services-to-new-customer-picture-id1281341046" class="d-block w-100" alt="BankImage2" width="300" height="700" style="padding:20px">
          <div class="carousel-caption d-none d-md-block bg-black">
            <h5>We Value our Customers</h5>
            <p>Customers are first priority for our bank.</p>
          </div>
          </div>
          <div class="carousel-item">
            <img src="https://images.unsplash.com/photo-1579621970795-87facc2f976d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80" class="d-block w-100" alt="BankImage3" width="300" height="700" style="padding:20px">
          <div class="carousel-caption d-none d-md-block bg-black">
            <h5>We Grow your Money</h5>
            <p>Yearly good interest rates are available to increase your money.</p>
          </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>


{% endblock body%}

templates/login.html
{% extends 'base.html' %}
{% block title %} login {% endblock title %}
{% block body %}


<div class="container">
      <div class="col-md-6 mx-auto text-center">
         <div class="header-title">
            <h1 class="wv-heading--title">
               Please sign in
            </h1>
         </div>
      </div>
    <div class="myform form ">
        <form action"/login" method="post" >
        {% csrf_token %}             
            <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name = "email">
            <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
            <label for="floatingPassword">Password</label>
            </div>
            <button class="btn btn-primary" type="submit">Sign in</button>
        </form>
    </div>
  </div>    

    <h class="h3 mb-3 fw-normal">Don't have account <a href = "/signup">Sign Up</a></h1>


{% endblock body%}

templates/services.html
{% extends 'base.html' %}
{% block title %} Services {% endblock title %}
{% block body %}
This is my Services body
{% endblock body%}

templates/signin.html
{% extends 'base.html' %}
{% block title %} login {% endblock title %}
{% block body %}
<h1> Log In </h1>
   
<form method = "POST">
   {% csrf_token %}
   <section class = "form-control">
      <h3> Enter Login Details</h3>
      {{form}}
      <input type="submit" name="submit" value="Log In"/>
      <a href="\signup">Sign Up For Free</a>
      </section>
</form>
</div>
{% endblock body%}

templates/signup.html
{% extends 'base.html' %}
{% block title %} signup {% endblock title %}
{% block body %}
   <div class = "signup">
   {% if messages %}
      <ul>
         {% for message in messages %}
         <li>{{message}}</li>
         {%endfor%}
      </ul>
   {% endif %}
   <h1> Create Account </h1>
   
<form method = "POST">
   {% csrf_token %}
   <section class = "form-control">
      <h3> Enter Your  Login Details</h3>
      {{form}}
      <h3> Enter Personal Details</h3>
      
        <div class="mb-3">
          <label for="name" class="form-label">Full Name</label>
          <input type="name" class="form-control" id="name" name="name">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" name="email" >
          </div>
        <div class="mb-3">
          <label for="phone" class="form-label">Phone Number</label>
          <input type="number" class="form-control" id="phone" name="phone">
        </div>
        <div class="mb-3">
            <label for="cnic" class="form-label">CNIC Number</label>
            <input type="number" class="form-control" id="cnic" name="cnic" >
          </div>
        </div>
      <input type="submit" name="submit" value="Register"/>
      </section>
</form>
</div>
{% endblock body%}

templates/user_account.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}Dashboard{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Bank Database Management System</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About us</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/services" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Services
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/services">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/faqs">FAQs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contact">Contact us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signout">Log Out</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- Optional JavaScript; choose one of the two! -->
{% if messages%}
{%for message in messages%}
<div class="alert alert-{{message.tags}}" role="alert">
  {{message}}
</div>
  {% endfor %}
  {% endif %}
    {% block body %} 
    
<table width=70% height=60%>
    <tr>
        <td>

            <div id="page_name" style="float:left;">
                <font color="#3399ff">User Account</font>
            </div>
        </td>
        <td>
            <div id="edit_details" style="float:right;">
                <button type="button" id="edit_button"><a href="{% url 'clients:dashboard' %}">Home</a></button>
            </div>
        </td>
    </tr>

    <tr>
        <td>
            <div id="details_box" align="center">
                <h4>User Details: </h4>
                <table id="details_table" cellpadding=5px;>
                    <tr>
                        <td>User Name : {{ customer.name }} </td>
                        <td id="name"></td>
                    </tr>
                </table>
            </div>
        </td>
        <td>
        <form name="dashboard" action="get_function_choosen">
            <input type="hidden" name="function_chosen" id="function_chosen">
            <div id="buttons_box">
                <table id="buttons_table" cellpadding=5px;>

                    <tr>
                        <td><button id="buttons" class="button" onclick="set_function_chosen('view_personal_information')">View Personal Info</button></td>
                    </tr>
                    <tr>
                        <td><button  id="buttons" onclick="set_function_chosen('withdraw')">   Withdraw   </button></td>
                    </tr>
                    <tr>
                        <td><button  id="buttons" onclick="set_function_chosen('deposit')">   Deposit    </button></td>
                    </tr>
                    <tr>
                        <td><button id="buttons" onclick="set_function_chosen('money_transfer')"> Money Transfer</button></td>
                    </tr>
                    <tr>
                        <td><button  id="buttons" onclick="set_function_chosen('balance_enquiry')">  Balance Enquiry   </button></td>
                    </tr>
                    <tr>
                      <td><button id="buttons" onclick="set_function_chosen('accout_modification')">Account Modification</button></td>
                    </tr>
                    <tr>
                      <td><button id="buttons" onclick="set_function_chosen('Mobile_Balance')">Mobile Recharge</button></td>
                    </tr>

                    <tr>
                      <td><button id="buttons" onclick="set_function_chosen('Account_Deletion')">Delete Your Account</button></td>
                    </tr>
                </table>
            </div>
        </form>
        </td>
    </tr>
</table>

<script>
function set_function_chosen(menu_name){

    hidden_field = document.getElementById("function_chosen");
    hidden_field.setAttribute("value", menu_name);
}
</script>

{% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>

</html>

templates/withdraw.html
{% extends 'user_account.html' %}
{% block title %} Withdraw {% endblock title %}
{% block body %}
<table width=70% height=60%>
<div id="edit_details" style="float:right;">
    <button type="button" id="edit_button"><a href="{% url 'clients:dashboard' %}">Home</a></button>
</div>
<tr>
    <td></td>

    <td>

        <div id="details_box">
            <form name="withdraw_details" action="withdraw" method="POST">
                <table id="details_table" cellpadding=5px;>
                    {% if accounts %}
                    {% csrf_token %}
                    <tr>
                        <td>Amount to be withdrawn :</td>
                        <td><input type="text" name="amount" placeholder="Amount"></td>
                    </tr>
                    <tr>
                        <td> Withdraw from account :  {{ accounts.Accno }}</td>
                    </tr>

                    <tr>
                        <td></td>
                        <!--<td><input type="button" value="Withdraw"></td>-->
                        <td><button>Withdraw</button></td>
                    </tr>
                    {% else %}
                        <tr> <td> New Customer. No accounts yet. </td></tr>
                    {% endif %}
                    <tr>
                        <td><span>{{msg|safe}}</span></td>
                    </tr>
                    <tr>
                        <td> <small>By Withdrawing money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br></td>
                    </tr>
                </table>
            </form>
            
           
            
        </div>
    </td>
</tr>
</table>
{% endblock body%}